Repository MOVIEBOOKIE/MOVIEBOOKIE_FE, pull requests merged in 2025-08, with the labels that each got.

#303 [Refactor/#302] 기능 QA 반영, global.css관심사 분리, 라이팅 수정
  next.config.ts
  public/images/custom-bg.png
  public/images/landing/randing-1.png
  public/images/landing/randing-2.png
  public/images/landing/randing-3.png
  public/landing/randing-1.webp
  public/landing/randing-2.webp
  public/landing/randing-3.webp
  src/app/(fullscreen)/category/[category]/client.tsx
  src/app/(fullscreen)/search/_components/category-button.tsx
  src/app/(fullscreen)/search/page.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/(tabs)/notifications/page.tsx
  src/app/_components/ServiceWorkerDebug.tsx
  src/app/_components/bottom-navibar.tsx
  src/app/_constants/categories.ts
  src/app/_constants/category-map.ts
  src/app/_styles/base.css
  src/app/_styles/globals.css
  src/app/_styles/theme.css
  src/app/_styles/utilities.css
  src/app/layout.tsx
  src/app/loading.tsx
Labels: 🎨 Desgin, 🔄 Refactor

#307 [Bug/#306] 유형결과 페이지 에러해결, css색상 수정
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/intro/page.tsx
  src/app/(fullscreen)/trait/result/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_components/bottom-navibar.tsx
  src/app/_components/main-card.tsx
  src/app/_constants/metadata.ts
  src/app/_styles/base.css
Labels: 🎨 Desgin, 🐞 BugFix

#309 [Refactor/#308] 디자인 QA)라이팅, 화질, 모달변경
  public/images/trait/movie1.png
  public/images/trait/movie10.png
  public/images/trait/movie2.png
  public/images/trait/movie3.png
  public/images/trait/movie4.png
  public/images/trait/movie5.png
  public/images/trait/movie6.png
  public/images/trait/movie7.png
  public/images/trait/movie8.png
  public/images/trait/movie9.png
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/detail/_components/share-modal.tsx
  src/app/(fullscreen)/search/_components/category-button.tsx
  src/app/(fullscreen)/search/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_constants/event-categories.ts
Labels: 🎨 Desgin

#311 [Design/#310] 디자인QA) 이벤트토글탭 변경, 이메일드롭다운,마이페이지 css 변경
  next.config.ts
  src/app/(fullscreen)/(my-page)/accounts/page.tsx
  src/app/(fullscreen)/(my-page)/withdraw/page.tsx
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/detail/_components/information-tab.tsx
  src/app/(fullscreen)/detail/_components/share-modal.tsx
  src/app/(fullscreen)/event-create/components/cinema-skeleton-card.tsx
  src/app/(fullscreen)/event-create/components/step1-category.tsx
  src/app/(fullscreen)/event-create/components/step5-people.tsx
  src/app/(fullscreen)/event-create/components/step6-place.tsx
  src/app/(fullscreen)/event-create/components/step7-writing.tsx
  src/app/(fullscreen)/event-create/page.tsx
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/event/success/_components/step1.tsx
  src/app/(fullscreen)/event/ticket/[id]/page.tsx
  src/app/(fullscreen)/event/ticket/_components/client.tsx
  src/app/(fullscreen)/ticket/components/ticket-card.tsx
  src/app/(fullscreen)/ticket/components/ticket-skeleton-card.tsx
  src/app/(fullscreen)/ticket/page.tsx
  src/app/(fullscreen)/verify/email/page.tsx
  src/app/(fullscreen)/verify/phone/page.tsx
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/event/_components/ticket-card.tsx
  src/app/(tabs)/event/_components/ticket-tab.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/_apis/events/participation.ts
  src/app/_components/complete.tsx
  src/app/_components/main-card.tsx
  src/app/_components/modal.tsx
  src/app/_constants/event-tab.ts
  src/app/_constants/paths.ts
  src/app/_hooks/events/use-event-tab-query.ts
  src/app/_styles/base.css
  src/icons/index.tsx
  src/icons/ui/mypage-feedback.svg
  src/icons/ui/mypage-ticket.svg
  src/middleware.ts
Labels: 🎨 Desgin, 📬 API

#315 [Refactor/#313] 날짜선택시 가능한지 요청 api연결 ,생성신청 실패 에러처리, 티켓상세 UI오류해결, OG태그추가
  public/custom-sw.js
  scripts/generate-firebase-config.js
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/detail/_components/share-modal.tsx
  src/app/(fullscreen)/event-create/components/step5-people.tsx
  src/app/(fullscreen)/event-create/page.tsx
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/ticket/[id]/page.tsx
  src/app/(fullscreen)/ticket/components/card-back.tsx
  src/app/(fullscreen)/ticket/components/card-front-skeleton.tsx
  src/app/(fullscreen)/ticket/components/card-front.tsx
  src/app/(fullscreen)/ticket/components/client.tsx
  src/app/(fullscreen)/ticket/components/ticket-card.tsx
  src/app/(tabs)/event/_components/event-tabs-client.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/notifications/components/item.tsx
  src/app/(tabs)/notifications/page.tsx
  src/app/_apis/events/participation.ts
  src/app/_apis/register-fcm-token.ts
  src/app/_components/ServiceWorkerDebug.tsx
  src/app/_constants/event-create.ts
  src/app/_constants/metadata.ts
  src/app/_hooks/fcm/use-fcm-handler.ts
  src/app/_hooks/fcm/use-fcm.ts
  src/app/_hooks/onboarding/use-kakao-login.ts
  src/app/_hooks/use-smart-noti-polling.ts
  src/app/_utils/dev-logger.ts
  src/app/error.tsx
Labels: 🐞 BugFix, 🔄 Refactor

#323 [Feat/deploy] dev/main 브랜치별 버셀 자동 배포
  .github/workflows/git-push.yml
  next.config.ts
Labels: 🌏 Deploy

#327 [fix/#326] 리다이렉트오류 로그 추가
  src/app/(fullscreen)/login/kakao/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_hooks/onboarding/use-kakao-login.ts
  src/app/_hooks/use-small-screen.ts
  src/middleware.ts
Labels: 🐞 BugFix

#329 [Design/#328] 노치를 위한 메타태그 추가
  src/app/layout.tsx
Labels: ✨ Feature, 🎨 Desgin

#334 [Design/#333] 뒤로가기 위치 수정 및 디테일 페이지 디자인 수정
  src/app/(fullscreen)/detail/_components/top-bar.tsx
  src/app/_components/detail-content.tsx
  src/app/_components/header.tsx
  src/app/_styles/base.css
  src/app/_styles/utilities.css
Labels: 🎨 Desgin

#338 [Fix/redirect] 운영서버 분리, 카테고리페이지 레이아웃 수정
  README.md
  next.config.ts
  public/images/readme.png
  src/app/(fullscreen)/category/[category]/client.tsx
  src/app/(fullscreen)/feedback/page.tsx
  src/middleware.ts
  vercel.json
Labels: 🌏 Deploy, 🎨 Desgin, 🐞 BugFix

#342 [Test/#322] 테스트환경세팅, 마이페이지/유틸 초기테스트, 캐러셀 수정
  README.md
  jest.config.js
  jest.setup.ts
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/__mocks__/next/navigation.ts
  src/app/(fullscreen)/event-create/components/period-calendar.tsx
  src/app/(tabs)/home/_components/carousel.tsx
  src/app/(tabs)/my-page/__tests__/page.test.tsx
  src/app/_components/button.test.tsx
  src/app/_utils/__tests__/deadline-utils.test.ts
  src/app/_utils/deadline-utils.ts
  vercel.json
Labels: 🐞 BugFix, ✅ Test

#349 [fix/#347] 노치대응 헤더영역 수정
  src/app/(fullscreen)/detail/_components/top-bar.tsx
  src/app/(fullscreen)/search/page.tsx
  src/app/(fullscreen)/trait/result/page.tsx
  src/app/(tabs)/home/_components/empty-carousel.tsx
  src/app/_components/header.tsx
Labels: 🎨 Desgin

#353 [Refactor/#344] 지도 네이버로 변경 및 연결
  src/app/(fullscreen)/detail/_components/map-thumbnail.tsx
  src/app/api/naver-map/route.ts
Labels: 🔄 Refactor

#354 [Design/#351] 노치대응 헤더 아이콘 위치 수정
  src/app/_components/header.tsx
  src/app/_styles/base.css
Labels: 🐞 BugFix

#356 [Bug/#355] 인증이메일 수정, 인증로직 로딩스피너 추가
  src/app/(fullscreen)/verify/email/page.tsx
  src/app/(fullscreen)/verify/phone/page.tsx
  src/app/(fullscreen)/verify/verify-number/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/_components/fixed-layout.tsx
  src/app/_components/header.tsx
  src/app/_styles/base.css
Labels: 🐞 BugFix, 🔄 Refactor

#359 [Bug/#357] 캐러셀 스크롤 수정, motion 추가
  src/app/(fullscreen)/event/success/_components/step1.tsx
  src/app/(fullscreen)/trait/_components/motion.ts
  src/app/(fullscreen)/trait/result/page.tsx
  src/app/(tabs)/home/_components/carousel.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_components/complete.tsx
  src/app/_components/detail-content.tsx
  src/app/_components/modal.tsx
  src/app/_components/type-list.tsx
  src/app/_utils/text-motion.ts
Labels: 🎨 Desgin, 🐞 BugFix
