Repository MOVIEBOOKIE/MOVIEBOOKIE_FE, pull requests merged in 2025-05, with the labels that each got.

#18 [Feature/#17] 메인 스와이프 후 화면 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/app/(route)/category/page.tsx
  src/app/(route)/search/page.tsx
  src/app/_components/bottom-navibar.tsx
  src/app/_components/button.tsx
  src/app/_components/carousel.tsx
  src/app/_components/index.ts
  src/app/_components/input.tsx
  src/app/_components/light-effect.tsx
  src/app/_constants/categories.ts
  src/app/_constants/index.ts
  src/app/_constants/navigation-tabs.ts
  src/app/_constants/paths.ts
  src/app/_mocks/movie-list.ts
  src/app/_styles/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/icons/index.tsx
  src/icons/search.svg
  tsconfig.json
Labels: ✨ Feature, 🎨 Desgin

#23 [Refactor/#22] 하단바 레이아웃 분리
  .github/auto_assign.yml
  .github/workflows/auto-comment.yml
  .github/workflows/auto_assign.yml
  src/app/(fullscreen)/category/page.tsx
  src/app/(fullscreen)/event-ticket/.gitkeep
  src/app/(fullscreen)/intro/page.tsx
  src/app/(fullscreen)/layout.tsx
  src/app/(fullscreen)/login/_components/.gitkeep
  src/app/(fullscreen)/login/page.tsx
  src/app/(fullscreen)/search/page.tsx
  src/app/(fullscreen)/verify1-phone/.gitkeep
  src/app/(fullscreen)/verify2-email/.gitkeep
  src/app/(fullscreen)/verify3-profile/.gitkeep
  src/app/(tabs)/event/_components/.gitkeep
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/layout.tsx
  src/app/(tabs)/my-page/_components/.gitkeep
  src/app/(tabs)/my-page/page.tsx
  src/app/(tabs)/page.tsx
  src/app/layout.tsx
Labels: 🔄 Refactor

#24 [Feature/#19] 검색 페이지 퍼블리싱
  next.config.ts
  public/drama.png
  public/movie.png
  public/popular.png
  public/recent.png
  src/app/(fullscreen)/category/[category]/page.tsx
  src/app/(fullscreen)/search/_components/category-button.tsx
  src/app/(fullscreen)/search/page.tsx
  src/app/_components/input.tsx
  src/app/_constants/event-categories.ts
  src/app/_constants/index.ts
  src/app/_constants/paths.ts
  src/icons/back.svg
  src/icons/index.tsx
Labels: ✨ Feature, 🎨 Desgin

#28 [Feature/#27] 인증플로우 UI, Header, StepText, 알림탭 추가
  .github/workflows/auto-comment.yml
  .github/workflows/auto_assign.yml
  src/app/(fullscreen)/login/page.tsx
  src/app/(fullscreen)/set-profile/page.tsx
  src/app/(fullscreen)/verify/_components/code-step.tsx
  src/app/(fullscreen)/verify/_components/email-step.tsx
  src/app/(fullscreen)/verify/_components/phone-step.tsx
  src/app/(fullscreen)/verify/_components/verify-number.tsx
  src/app/(fullscreen)/verify/page.tsx
  src/app/(tabs)/notifications/page.tsx
  src/app/(tabs)/page.tsx
  src/app/_components/header.tsx
  src/app/_components/index.ts
  src/app/_components/input.tsx
  src/app/_components/light-effect.tsx
  src/app/_components/step-header.tsx
  src/app/_constants/navigation-tabs.ts
  src/app/_constants/paths.ts
  src/app/_utils/format-phone.ts
  src/icons/common/back.svg
  src/icons/common/close.svg
  src/icons/common/logo-white.svg
  src/icons/index.tsx
  src/icons/tab/Notification.svg
  src/icons/tab/event.svg
  src/icons/tab/home.svg
  src/icons/tab/light.svg
  src/icons/tab/my.svg
  src/icons/ui/arrow-down.svg
  src/icons/ui/default-profile.svg
  src/icons/ui/kakao.svg
  src/icons/ui/search.svg
  src/icons/ui/swipe-down.svg
Labels: ✨ Feature, 🎨 Desgin

#32 [Feature/#25] 사용자 유형 테스트 페이지 구현
  package.json
  pnpm-lock.yaml
  public/images/custom-bg.png
  public/images/drama.png
  public/images/favicon.png
  public/images/image.png
  public/images/movie.png
  public/images/popular.png
  public/images/recent.png
  src/app/(fullscreen)/intro/page.tsx
  src/app/(fullscreen)/layout.tsx
  src/app/(fullscreen)/trait/_components/step0.tsx
  src/app/(fullscreen)/trait/_components/step1.tsx
  src/app/(fullscreen)/trait/_components/step2.tsx
  src/app/(fullscreen)/trait/_components/step3.tsx
  src/app/(fullscreen)/trait/_components/type-list.tsx
  src/app/(fullscreen)/trait/page.tsx
  src/app/(tabs)/layout.tsx
  src/app/(tabs)/page.tsx
  src/app/_components/button.tsx
  src/app/_components/header.tsx
  src/app/_constants/category-map.ts
  src/app/_constants/paths.ts
  src/app/_constants/trait.tsx
  src/app/_styles/globals.css
  src/icons/ball.svg
  src/icons/camcorder.svg
  src/icons/index.tsx
  src/icons/popcorn.svg
  src/icons/smile.svg
  src/icons/television.svg
  src/icons/trait/desert.svg
  src/icons/trait/dizziness.svg
  src/icons/trait/document.svg
  src/icons/trait/fire.svg
  src/icons/trait/grin.svg
  src/icons/trait/party.svg
  src/icons/trait/sad.svg
  src/icons/trait/speaking.svg
  src/icons/trait/speech-bubble.svg
  src/icons/trait/target.svg
  src/icons/trait/yawn.svg
Labels: ✨ Feature, 🎨 Desgin

#31 [Feature/#29] 카테고리 페이지 UI
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/app/(fullscreen)/category/[category]/client.tsx
  src/app/(fullscreen)/category/[category]/page.tsx
  src/app/(fullscreen)/verify/_components/email-step.tsx
  src/app/(tabs)/page.tsx
  src/app/_components/main-card.tsx
  src/app/_components/pagination.tsx
  src/app/_constants/categories.ts
  src/app/_constants/index.ts
  src/app/_mocks/movie-list.ts
  src/app/_types/card.ts
  src/icons/common/arrow-down.svg
  src/icons/common/arrow-left.svg
  src/icons/common/arrow-right.svg
  src/icons/index.tsx
Labels: ✨ Feature, 🎨 Desgin

#34 [Feature/#33] 사용자 유형 결과 페이지 구현
  pnpm-lock.yaml
  src/app/(fullscreen)/intro/page.tsx
  src/app/(fullscreen)/trait-result/page.tsx
  src/app/(fullscreen)/trait/page.tsx
  src/app/_constants/paths.ts
  src/icons/common/logo-white.svg
  src/icons/index.tsx
  src/icons/tab/notification.svg
Labels: ✨ Feature, 🎨 Desgin

#36 [Feature/#30] 이벤트탭 메인페이지 UI
  next.config.ts
  public/images/event-banner.png
  src/app/(tabs)/event/_components/.gitkeep
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/event/_components/event-toggle.tsx
  src/app/(tabs)/event/_components/ticket-card.tsx
  src/app/(tabs)/event/_components/ticket-tab.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/layout.tsx
  src/app/_components/main-card.tsx
  src/app/_constants/event-tab.ts
  src/app/_mocks/movie-list.ts
  src/app/_types/.gitkeep
  vercel.json
Labels: ✨ Feature, 🎨 Desgin

#45 [Bug/#44] 버셀 배포 오류 해결
  next.config.ts
  public/manifest.ts
  src/app/_mocks/movie-list.ts
  src/app/_mocks/movie-slides.ts
Labels: 🐞 BugFix

#46 [Bugfix] 기타 수정
  src/app/page.tsx
Labels: 🐞 BugFix

#47 [Bug/#41] 배포 404 에러
  src/app/(tabs)/home/page.tsx
  src/app/page.tsx
Labels: 🌏 Deploy, 🐞 BugFix

#50 [Setting/#49] 배포 자동화 테스트
  .github/workflows/deploy.yml
  build.sh
Labels: 🌏 Deploy

#42 [Design#38] header,하단 버튼 레이아웃 컴포넌트
  src/app/(fullscreen)/make-event/date/page.tsx
  src/app/(fullscreen)/make-event/page.tsx
  src/app/(fullscreen)/make-event/type/page.tsx
  src/app/(fullscreen)/set-profile/page.tsx
  src/app/(fullscreen)/trait-result/page.tsx
  src/app/(fullscreen)/trait/_components/step1.tsx
  src/app/(fullscreen)/trait/_components/step2.tsx
  src/app/(fullscreen)/trait/_components/step3.tsx
  src/app/(fullscreen)/trait/page.tsx
  src/app/(fullscreen)/verify/email/page.tsx
  src/app/(fullscreen)/verify/page.tsx
  src/app/(fullscreen)/verify/phone/page.tsx
  src/app/(fullscreen)/verify/verify-number/page.tsx
  src/app/(tabs)/event/page.tsx
  src/app/_components/fixedlayout.tsx
  src/app/_components/header.tsx
  src/app/_components/input.tsx
  src/app/_components/step-header.tsx
  src/app/_constants/event-categories.ts
  src/app/_constants/event-tab.ts
  src/app/_constants/index.ts
  src/app/_constants/path-images.ts
  src/app/_mocks/movie-list.ts
  src/app/_mocks/movie-slides.ts
  src/app/layout.tsx
Labels: 🎨 Desgin, 🔄 Refactor

#54 [Bug/#53] pwa 홈화면 추가 오류 해결
  public/images/favicon.png
  public/images/favicon/196x196.png
  public/manifest.json
  public/manifest.ts
  src/app/layout.tsx
Labels: 🐞 BugFix

#51 [Feature/#48] 카카오 로그인 API 연결
  next.config.ts
  package.json
  src/app/(fullscreen)/login/_components/.gitkeep
  src/app/(fullscreen)/login/kakao/page.tsx
  src/app/(fullscreen)/login/page.tsx
  src/app/(fullscreen)/make-event/page.tsx
  src/app/(fullscreen)/trait-result/page.tsx
  src/app/(fullscreen)/verify/verify-number/page.tsx
  src/app/_components/button.tsx
  src/app/_constants/login-slides.ts
  src/app/_constants/paths.ts
  src/app/_utils/api.ts
  src/app/api/auth/auth.ts
Labels: ✨ Feature, 📬 API

#56 [Bug/#55] 카카오 로그인 에러, 빌드 에러
  src/app/(fullscreen)/login/kakao/page.tsx
  src/app/_utils/api.ts
  src/app/api/auth/auth.ts
Labels: 🌏 Deploy, 📬 API

#57 [Feature/#52] pwa 설치유도 모달, 정보동의 UI
  package.json
  public/manifest.json
  src/app/(fullscreen)/agreement/components/item.tsx
  src/app/(fullscreen)/agreement/page.tsx
  src/app/(fullscreen)/login/page.tsx
  src/app/(tabs)/event/page.tsx
  src/app/_components/fixedlayout.tsx
  src/app/_components/header.tsx
  src/app/_components/index.ts
  src/app/_components/pwa-prompt-modal.tsx
  src/app/_utils/get-mobile.ts
  src/app/fonts/pretendard.ts
  src/app/layout.tsx
  src/icons/bell.svg
  src/icons/index.tsx
  src/icons/mail.svg
  src/icons/phone.svg
  src/icons/ui/share.svg
Labels: ✨ Feature, 🎨 Desgin

#61 [Feature/#35] 디테일페이지 퍼블리싱
  public/images/tmp-map.png
  public/images/tmp-movie.png
  src/app/(fullscreen)/detail/[detail]/page.tsx
  src/app/(fullscreen)/detail/_components/information-tab.tsx
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/_components/badge.tsx
  src/app/_components/carousel.tsx
  src/app/_components/index.ts
  src/app/_components/toggle-tab.tsx
  src/app/_constants/path-images.ts
  src/icons/common/upload.svg
  src/icons/index.tsx
Labels: ✨ Feature, 🎨 Desgin

#65 [Feature/#64] 완료 페이지 구현
  src/app/_components/complete.tsx
  src/app/_components/fixed-layout.tsx
  src/app/_constants/path-images.ts
  src/app/_mocks/mock-data.ts
  src/app/_mocks/movie-slides.ts
  src/icons/index.tsx
  src/icons/ui/complete.svg
Labels: ✨ Feature, 🎨 Desgin

#68 [Design/#67] FixedLayout 버튼 레이아웃 변경
  src/app/_components/fixed-layout.tsx
Labels: 🎨 Desgin

#69 [Feature/#66] step 백버튼, 더미데이터 추가, 인앱브라우저 변경
  public/mock_images/mock-image-19.png
  public/mock_images/mock-image-20.png
  public/mock_images/mock-image-21.png
  public/mock_images/mock-image-22.png
  public/mock_images/mock-image-23.png
  public/mock_images/mock-image-24.png
  public/mock_images/mock-image-25.png
  src/app/(fullscreen)/event-create/components/step1-category.tsx
  src/app/(fullscreen)/event-create/components/step6-place.tsx
  src/app/(fullscreen)/event-create/page.tsx
  src/app/(fullscreen)/login/kakao/page.tsx
  src/app/(fullscreen)/make-event/type/page.tsx
  src/app/(fullscreen)/trait/page.tsx
  src/app/_components/complete.tsx
  src/app/_components/fixed-layout.tsx
  src/app/_components/inapp-redirect.tsx
  src/app/_components/main-card.tsx
  src/app/_constants/path-images.ts
  src/app/_mocks/mock-data.ts
  src/app/_mocks/movie-slides.ts
  src/app/_types/card.ts
  src/app/layout.tsx
Labels: ✨ Feature, 🎨 Desgin

#72 [Feature/#70] 이벤트생성-모집글 UI
  src/app/(fullscreen)/event-create/components/post-textarea.tsx
  src/app/(fullscreen)/event-create/components/step3-time.tsx
  src/app/(fullscreen)/event-create/components/step6-place.tsx
  src/app/(fullscreen)/event-create/components/step7-writing.tsx
  src/app/(fullscreen)/event-create/page.tsx
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/event/success/_components/step1.tsx
  src/app/(fullscreen)/make-event/date/page.tsx
  src/app/(fullscreen)/make-event/type/page.tsx
  src/app/_components/detail-content.tsx
  src/app/_constants/path-images.ts
  src/app/_constants/paths.ts
  src/app/_mocks/mock-cinemas.ts
  src/icons/index.tsx
  src/icons/ui/image-delete.svg
  src/icons/ui/image.svg
Labels: ✨ Feature, 🎨 Desgin

#75 [Design/#74] manifest icon 추가
  public/images/favicon/128x128.png
  public/images/favicon/144x144.png
  public/images/favicon/152x152.png
  public/images/favicon/256x256.png
  public/images/favicon/384x384.png
  public/images/favicon/48x48.png
  public/images/favicon/512x512.png
  public/images/favicon/72x72.png
  public/images/favicon/96x96.png
  public/manifest.json
Labels: 🎨 Desgin

#85 [Feature/#84] 티켓 페이지 퍼블리싱
  src/app/(fullscreen)/event/ticket/_components/card-back.tsx
  src/app/(fullscreen)/event/ticket/_components/card-front.tsx
  src/app/(fullscreen)/event/ticket/_components/client.tsx
  src/app/(fullscreen)/event/ticket/page.tsx
  src/app/(fullscreen)/trait-result/page.tsx
  src/app/_styles/globals.css
  src/icons/index.tsx
  src/icons/ui/rotate.svg
Labels: ✨ Feature, 🎨 Desgin

#89 [Setting/#88] 자동 배포 설정
  .github/workflows/deploy.yml
  build.sh
  src/app/(fullscreen)/event/ticket/_components/card-front.tsx
Labels: ⚙ Setting

#90 [Feature/#87] 이벤트탭, 피드백페이지 , EmptyState UI
  public/images/empty-home.png
  public/images/event-banner.png
  src/app/(fullscreen)/category/[category]/client.tsx
  src/app/(fullscreen)/event-create/components/period-calendar.tsx
  src/app/(fullscreen)/event-create/components/step3-time.tsx
  src/app/(fullscreen)/event-create/components/step5-people.tsx
  src/app/(fullscreen)/feedback/page.tsx
  src/app/(fullscreen)/feedback/result/page.tsx
  src/app/(fullscreen)/login/kakao/page.tsx
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/event/_components/ticket-tab.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/_components/EmptyCarouselSlide.tsx
  src/app/_components/carousel.tsx
  src/app/_components/fixed-layout.tsx
  src/app/_constants/paths.ts
  src/icons/common/empty-ticket.svg
  src/icons/common/empty.svg
  src/icons/index.tsx
  src/icons/ui/kissingface.svg
  src/icons/ui/thinkingface.svg
Labels: ✨ Feature, 🎨 Desgin

#93 [Feature/#87] 배포 오류 해결
  src/app/(fullscreen)/event-create/components/period-calendar.tsx
  src/app/(fullscreen)/feedback/result/components/feedbackpage.tsx
  src/app/(fullscreen)/feedback/result/page.tsx
  src/app/_components/carousel.tsx
  src/app/_constants/feedback.ts
  src/app/_constants/index.ts
Labels: 🌏 Deploy, 🐞 BugFix

#97 [Feature/#95] 토스트, 공통모달 UI 구현
  src/app/_components/complete.tsx
  src/app/_components/modal.tsx
  src/app/_components/toast.tsx
  src/app/_styles/globals.css
  src/icons/index.tsx
  src/icons/ui/alert.svg
  src/icons/ui/check.svg
  src/icons/ui/checkbox.svg
Labels: ✨ Feature, 🎨 Desgin

#99 [Feature/#98] 로티 파일 적용
  package.json
  pnpm-lock.yaml
  src/app/loading.tsx
  src/lotties/loading.json
  tsconfig.json
Labels: ✨ Feature, 🎨 Desgin

#100 [Feature/#96] 카카오로그인, 이벤트 생성api 연결
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(fullscreen)/event-create/components/post-textarea.tsx
  src/app/(fullscreen)/event-create/page.tsx
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/event/success/_components/step1.tsx
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_components/detail-content.tsx
  src/app/_components/pwa-prompt-modal.tsx
  src/app/_components/user-initializer.tsx
  src/app/_hooks/useCreateEvent.ts
  src/app/_stores/.gitkeep
  src/app/_stores/useEventCreateForm.ts
  src/app/_stores/useUserStore.ts
  src/app/_styles/globals.css
  src/app/_types/event.ts
  src/app/_utils/api.ts
  src/app/_utils/axios.ts
  src/app/_utils/create-event-formdata.ts
  src/app/layout.tsx
  src/app/providers/react-query-provider.tsx
  src/lib/auth/sendAuthCodeToServer.ts
Labels: ✨ Feature, 📬 API

#107 [Design/#106] 타이포 수정 및 스크롤 제거
  src/app/(fullscreen)/layout.tsx
  src/app/(tabs)/home/page.tsx
  src/app/(tabs)/layout.tsx
  src/app/_styles/globals.css
Labels: 🎨 Desgin

#110 [Bug/#109] 빌드 오류 해결
  src/app/(fullscreen)/event/success/_components/step1.tsx
Labels: 🌏 Deploy, 🐞 BugFix

#108 [Feature/#102] 사용자 유형 결과 페이지 구현 및 API 연결
  public/images/trait/gradation-background.png
  public/images/trait/movie1.png
  public/images/trait/movie10.png
  public/images/trait/movie2.png
  public/images/trait/movie3.png
  public/images/trait/movie4.png
  public/images/trait/movie5.png
  public/images/trait/movie6.png
  public/images/trait/movie7.png
  public/images/trait/movie8.png
  public/images/trait/movie9.png
  src/app/(fullscreen)/trait-result/page.tsx
  src/app/(fullscreen)/trait/hooks/use-user-type.ts
  src/app/(fullscreen)/trait/page.tsx
  src/app/_components/line-break.tsx
  src/app/_constants/api.ts
  src/app/_constants/path-images.ts
  src/app/_types/user-type.ts
  src/app/apis/auth/user-type/user-type-queries.ts
  src/app/apis/auth/user-type/user-type.ts
  src/app/apis/instance.ts
  src/app/apis/methods.ts
  src/app/apis/type.ts
  src/app/layout.tsx
Labels: ✨ Feature, 📬 API

#112 [Bug/#111] 배포 빌드 오류 해결
  src/app/_components/detail-content.tsx
Labels: 🌏 Deploy, 🐞 BugFix

#117 [Bug] 배포 오류 수정
  src/app/(fullscreen)/event/success/_components/client-wrapper.tsx
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/event/success/_components/step1.tsx
  src/app/(fullscreen)/event/success/_components/step2.tsx
  src/app/(fullscreen)/event/success/page.tsx
Labels: 🌏 Deploy

#120 [Feature/lottie] 로티 추가
  package.json
  pnpm-lock.yaml
  src/app/loading.tsx
  src/lotties/loading.json
  tsconfig.json
Labels: ✨ Feature

#123 feat: 빌드오류 해결, 카카오로그인 axios 수정
  src/app/(fullscreen)/event-create/components/post-textarea.tsx
  src/app/(fullscreen)/event-create/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_components/detail-content.tsx
  src/app/_components/pwa-prompt-modal.tsx
  src/app/_stores/.gitkeep
  src/app/_stores/useEventCreateForm.ts
  src/app/_styles/globals.css
  src/app/_types/event.ts
  src/app/_utils/create-event-formdata.ts
  src/lib/auth/sendAuthCodeToServer.ts
Labels: ✨ Feature, 🌏 Deploy, 🎨 Desgin

#125 feat: qa 반영, success api 요청
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/event/success/_components/step1.tsx
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/event/page.tsx
  src/app/_hooks/use-create-event.ts
Labels: 🌏 Deploy, 📬 API

#126 fix: 타이포 수정, 스크롤 제거,useCreateEvent
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/layout.tsx
  src/app/(tabs)/home/page.tsx
  src/app/(tabs)/layout.tsx
  src/app/_hooks/use-create-event.ts
  src/app/_styles/globals.css
Labels: 🌏 Deploy, 🐞 BugFix, 📬 API

#127 [Feature/101 1] qa반영 css 수정, 캘린더 토스트 추가, 모달수정
  src/app/(fullscreen)/event-create/components/calendar.tsx
  src/app/(fullscreen)/event-create/components/period-calendar.tsx
  src/app/(fullscreen)/event-create/components/post-textarea.tsx
  src/app/_components/index.ts
  src/app/_components/modal.tsx
  src/app/_components/toast.tsx
  src/app/_hooks/use-user-info.ts
  src/app/_utils/format-phone.ts
  src/icons/index.tsx
  src/icons/ui/toast-alert.svg
Labels: 🎨 Desgin

#128 [Feature/101-2] 사용자인증 api, 인원제한, 캘린더 토스트 추가
  src/app/(fullscreen)/event-create/components/step5-people.tsx
  src/app/(fullscreen)/event-create/page.tsx
  src/app/(fullscreen)/login/kakao/page.tsx
  src/app/(fullscreen)/set-profile/page.tsx
  src/app/(fullscreen)/verify/email/page.tsx
  src/app/(fullscreen)/verify/phone/page.tsx
  src/app/(fullscreen)/verify/verify-number/page.tsx
  src/app/_constants/paths.ts
  src/app/_hooks/onboarding/useKakaoLogin.ts
  src/app/_hooks/onboarding/useSendCode.ts
  src/app/_hooks/onboarding/useVerifyCode.ts
Labels: 🎨 Desgin, 📬 API

#134 [Feature/#133] 이벤트생성, 마이페이지, 검색 css 수정
  src/app/(fullscreen)/event-create/components/step3-time.tsx
  src/app/(fullscreen)/event-create/components/step5-people.tsx
  src/app/(fullscreen)/event-create/components/step6-place.tsx
  src/app/(fullscreen)/event-create/components/step7-writing.tsx
  src/app/(fullscreen)/search/_components/category-button.tsx
  src/app/(fullscreen)/search/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/_components/input.tsx
  src/app/_constants/event-categories.ts
  src/icons/index.tsx
  src/icons/ui/default-profile.svg
  src/icons/ui/location.svg
Labels: 🎨 Desgin

#132 [Feature/#131] 이벤트탭: 만든이벤트 조회 API 연동
  public/images/event-banner.png
  src/app/(fullscreen)/category/[category]/client.tsx
  src/app/(fullscreen)/category/[category]/page.tsx
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/event/_components/ticket-card.tsx
  src/app/(tabs)/event/_components/ticket-tab.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_apis/events/participation.ts
  src/app/_apis/methods.ts
  src/app/_apis/type.ts
  src/app/_components/bottom-navibar.tsx
  src/app/_components/detail-content.tsx
  src/app/_components/main-card.tsx
  src/app/_components/toggle-tab.tsx
  src/app/_constants/api.ts
  src/app/_hooks/events/use-event-tab-query.ts
  src/app/_types/card.ts
  src/app/_utils/map-to-eventcard.ts
Labels: 🎨 Desgin, 📬 API

#139 [Feature/#138] 마이페이지 API 연결, 피드백 퍼블리싱 수정
  src/app/(fullscreen)/event-completed/page.tsx
  src/app/(fullscreen)/feedback/page.tsx
  src/app/(fullscreen)/feedback/result/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/_apis/auth/mypage.ts
  src/app/_apis/methods.ts
  src/app/_apis/type.ts
  src/app/_hooks/auth/use-mypage.tsx
Labels: 🎨 Desgin, 📬 API

#142 [Feature/#135] 디테일 페이지 API 연결
  next.config.ts
  pnpm-lock.yaml
  src/app/(fullscreen)/detail/[detail]/page.tsx
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/detail/_components/information-tab.tsx
  src/app/(fullscreen)/detail/_components/top-bar.tsx
  src/app/(fullscreen)/event-create/page.tsx
  src/app/(fullscreen)/event/success/_components/client-wrapper.tsx
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/event/success/_components/step1.tsx
  src/app/(fullscreen)/event/success/_components/step2.tsx
  src/app/(fullscreen)/event/success/page.tsx
  src/app/(fullscreen)/login/login-swiper.tsx
  src/app/(fullscreen)/login/page.tsx
  src/app/(fullscreen)/trait-result/page.tsx
  src/app/(fullscreen)/trait/hooks/use-user-type.ts
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/_apis/ event/event.ts
  src/app/_apis/ event/use-event-querise.ts
  src/app/_components/detail-content.tsx
  src/app/_components/lottie.tsx
  src/app/_components/pwa-prompt-modal.tsx
  src/app/_components/user-initializer.tsx
  src/app/_constants/api.ts
  src/app/_hooks/use-event.ts
  src/app/_hooks/useCreateEvent.ts
  src/app/_stores/useUserStore.ts
  src/app/_types/event.ts
  src/app/_utils/axios.ts
  src/app/apis/auth/user-type/user-type-queries.ts
  src/app/apis/auth/user-type/user-type.ts
  src/app/apis/instance.ts
  src/app/apis/methods.ts
  src/app/apis/type.ts
  src/app/layout.tsx
Labels: ✨ Feature

#145 [Refactor/#144] 불필요한 파일 및 코드 삭제
  public/mock_images/mock-image-1.png
  public/mock_images/mock-image-10.png
  public/mock_images/mock-image-11.png
  public/mock_images/mock-image-12.png
  public/mock_images/mock-image-13.png
  public/mock_images/mock-image-14.png
  public/mock_images/mock-image-15.png
  public/mock_images/mock-image-16.png
  public/mock_images/mock-image-17.png
  public/mock_images/mock-image-18.png
  public/mock_images/mock-image-19.png
  public/mock_images/mock-image-2.png
  public/mock_images/mock-image-20.png
  public/mock_images/mock-image-21.png
  public/mock_images/mock-image-22.png
  public/mock_images/mock-image-23.png
  public/mock_images/mock-image-24.png
  public/mock_images/mock-image-25.png
  public/mock_images/mock-image-3.png
  public/mock_images/mock-image-4.png
  public/mock_images/mock-image-5.png
  public/mock_images/mock-image-6.png
  public/mock_images/mock-image-7.png
  public/mock_images/mock-image-8.png
  public/mock_images/mock-image-9.png
  public/mock_images/place-1.png
  public/mock_images/place-2.png
  public/mock_images/place-3.png
  src/app/(fullscreen)/event/ticket/_components/card-front.tsx
  src/app/_constants/path-images.ts
  src/app/_mocks/mock-cinemas.ts
  src/app/_mocks/movie-slides.ts
Labels: 🔄 Refactor

#147 [Feature/#146] 초기 진입 로직 추가
  src/app/(fullscreen)/event/ticket/_components/card-front.tsx
  src/app/_mocks/mock-data.ts
  src/app/loading.tsx
  src/lotties/loading.json
  src/middleware.ts
Labels: ✨ Feature

#155 [Fix/store] GlobalLoading추가, API 연동 수정
  src/app/(fullscreen)/login/kakao/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_apis/auth/mypage.ts
  src/app/_apis/instance.ts
  src/app/_components/carousel.tsx
  src/app/_components/global-loading.tsx
  src/app/_hooks/auth/use-mypage.tsx
  src/app/_stores/useUserStore.ts
  src/app/layout.tsx
Labels: ✨ Feature, 📬 API

#159 [Feature/#153] 이벤트 신청, 취소, 모집 취소 API 연결 및 토스트 수정
  src/app/(fullscreen)/(my-page)/withdraw/page.tsx
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/detail/_constants/detail.ts
  src/app/(fullscreen)/event-create/page.tsx
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/_apis/events/event-queries.ts
  src/app/_apis/events/events.ts
  src/app/_components/complete.tsx
  src/app/_components/modal.tsx
  src/app/_components/toast-renderer.tsx
  src/app/_constants/api.ts
  src/app/_hooks/events/use-events.ts
  src/app/_stores/use-toast-store.ts
  src/app/layout.tsx
Labels: ✨ Feature, 📬 API

#169 [Feature/#164] 카테고리 탭+더보기/ 카테고리 페이지 API연결, FCM 초기세팅
  firebase-config.ts
  package.json
  pnpm-lock.yaml
  public/firebase-messaging-sw.js
  src/app/(fullscreen)/(my-page)/accounts/page.tsx
  src/app/(fullscreen)/category/[category]/client.tsx
  src/app/(fullscreen)/category/[category]/page.tsx
  src/app/(fullscreen)/event-create/components/step7-writing.tsx
  src/app/(fullscreen)/login/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_apis/events/category.ts
  src/app/_components/fcm/fcm-listener.tsx
  src/app/_components/fcm/noti-test.tsx
  src/app/_components/main-card.tsx
  src/app/_components/pwa-prompt-modal.tsx
  src/app/_hooks/events/use-category-events.ts
  src/app/_hooks/use-fcm.ts
  src/app/_utils/format-time-ago.ts
  src/app/_utils/map-to-eventcard.ts
  src/app/layout.tsx
  src/lib/auth/sendAuthCodeToServer.ts
  src/middleware.ts
  src/scripts/generate-firebase-config.js
  tsconfig.json
Labels: ⚙ Setting, 📬 API

#170 [Feature/#168] 상세페이지 대관 및 이벤트 API 연결
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/detail/_components/alert-content.tsx
  src/app/(fullscreen)/detail/_components/event-status.tsx
  src/app/(fullscreen)/detail/_constants/detail.tsx
  src/app/(fullscreen)/event/ticket/_components/client.tsx
  src/app/_apis/events/events.ts
  src/app/_apis/methods.ts
  src/app/_apis/ticket/ticket-queries.ts
  src/app/_apis/ticket/ticket.ts
  src/app/_components/detail-content.tsx
  src/app/_constants/api.ts
  src/app/_constants/paths.ts
  src/app/_hooks/events/use-events.ts
  src/app/_hooks/ticket/use-ticket.ts
  src/app/_types/event.ts
  src/app/_types/ticket.ts
  src/icons/index.tsx
  src/icons/ui/check-alert.svg
  src/icons/ui/danger.svg
Labels: ✨ Feature, 📬 API

#176 [Feature/#174] FCM 알림구현, 알림탭 연결
  public/firebase-messaging-sw.js
  src/app/(fullscreen)/(my-page)/accounts/page.tsx
  src/app/(fullscreen)/event-completed/[id]/page.tsx
  src/app/(fullscreen)/feedback/page.tsx
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/(tabs)/notifications/components/item.tsx
  src/app/(tabs)/notifications/components/target-url.ts
  src/app/(tabs)/notifications/page.tsx
  src/app/_apis/noti.ts
  src/app/_components/fcm/fcm-listener.tsx
  src/app/_components/fcm/noti-test.tsx
  src/app/_components/main-card.tsx
  src/app/_constants/paths.ts
  src/app/_hooks/auth/use-logout.ts
  src/app/_hooks/events/use-event-tab-query.ts
  src/app/_hooks/use-fcm.ts
  src/app/_stores/use-noti.ts
  src/app/_types/card.ts
  src/app/_types/noti.ts
  src/app/_utils/format-time-ago.ts
  src/app/_utils/map-noti.ts
  src/app/lib/firebase-notification.ts
  src/app/lib/firebase.ts
  src/icons/ui/noti-check.svg
  src/icons/ui/noti-confirm.svg
Labels: ✨ Feature, 🎨 Desgin, 📬 API

#179 [Feature/#178] QA: 이벤트 생성 css 수정
  src/app/(fullscreen)/event-create/components/period-calendar.tsx
  src/app/(fullscreen)/event-create/components/step4-period.tsx
  src/app/(fullscreen)/event-create/components/step6-place.tsx
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(tabs)/notifications/components/target-url.ts
  src/app/_constants/paths.ts
Labels: 🎨 Desgin

#183 [Feature/#180]이벤트 최신순 정렬, 배포주소에서 알림 안뜨는 이슈
  public/firebase-messaging-sw.js
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/notifications/page.tsx
  src/app/_stores/use-noti.ts
Labels: 🐞 BugFix

#186 [Feature/#184] store 값으로 유저조회, 소셜계정 페이지 UI
  public/firebase-messaging-sw.js
  src/app/(fullscreen)/(my-page)/accounts/page.tsx
  src/app/(fullscreen)/login/kakao/page.tsx
  src/app/(fullscreen)/set-profile/page.tsx
  src/app/(fullscreen)/trait-result/page.tsx
  src/app/(fullscreen)/trait/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_apis/auth/mypage.ts
  src/app/_hooks/auth/use-mypage.ts
  src/app/_stores/useUserStore.ts
  src/app/_types/user-profile.ts
  src/app/layout.tsx
Labels: ✨ Feature, 🎨 Desgin

#192 [Feature/#182] 검색 API 연결
  package.json
  pnpm-lock.yaml
  src/app/(fullscreen)/search/page.tsx
  src/app/_apis/events/event-queries.ts
  src/app/_apis/events/events.ts
  src/app/_components/input.tsx
  src/app/_constants/api.ts
  src/app/_hooks/events/use-events.ts
  src/app/_types/event.ts
Labels: ✨ Feature, 📬 API

#195 [Bug/#193] 메인 페이지 스크롤 문제 해결 및 상태관리 오류 해결
  package.json
  pnpm-lock.yaml
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/event-create/components/post-textarea.tsx
  src/app/(fullscreen)/event-create/components/step7-writing.tsx
  src/app/(fullscreen)/trait/_components/step1.tsx
  src/app/(fullscreen)/trait/_components/step2.tsx
  src/app/(fullscreen)/trait/_components/step3.tsx
  src/app/(fullscreen)/trait/result/page.tsx
  src/app/(tabs)/home/_components/carousel.tsx
  src/app/(tabs)/home/_components/empty-carousel.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_components/detail-content.tsx
  src/app/_components/index.ts
  src/app/_constants/detail.tsx
Labels: ✨ Feature, 🎨 Desgin, 🐞 BugFix

#198 [Bug/#196] 상세페이지 오류 수정
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/detail/_components/share-modal.tsx
  src/app/_components/modal.tsx
Labels: 🐞 BugFix

#200 [Fix/noti1] 티켓, 랜딩이미지 수정, 알림 테스트
  next.config.ts
  public/custom-sw/sw.js
  public/images/landing/randing-1.png
  public/images/landing/randing-2.png
  public/images/landing/randing-3.png
  src/app/(tabs)/event/_components/ticket-card.tsx
  src/app/(tabs)/event/_components/ticket-tab.tsx
  src/app/_constants/login-slides.ts
  src/app/layout.tsx
  src/app/lib/firebase-notification.ts
Labels: 🎨 Desgin, 🐞 BugFix

#204 [bug/#203]블러 아이콘 png 로 수정, 하단탭 안보이는 문제 해결
  public/images/share-link.png
  src/app/(fullscreen)/detail/_components/share-modal.tsx
  src/app/(tabs)/layout.tsx
  src/middleware.ts
Labels: 🐞 BugFix

#207 [Bug/#205] 홈에서 카테고리 스크롤 위치저장, 스켈레톤 적용,
  public/images/share-link.png
  src/app/(fullscreen)/category/[category]/client.tsx
  src/app/(fullscreen)/detail/_components/top-bar.tsx
  src/app/(fullscreen)/event-create/components/calendar.tsx
  src/app/(fullscreen)/event-create/components/period-calendar.tsx
  src/app/(fullscreen)/search/page.tsx
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_components/global-loading.tsx
  src/middleware.ts
Labels: 🐞 BugFix

#209 [Bug/build12] 빌드오류 해결
  public/images/landing/randing-1.png
  public/images/landing/randing-2.png
  public/images/landing/randing-3.png
  src/app/(fullscreen)/detail/[id]/page.tsx
Labels: 🐞 BugFix

#213 [Feature/#212] fcm 토스트 알림 테스트
  public/custom-sw/sw.js
  public/firebase-config.js
  src/app/_apis/noti.ts
  src/app/_components/fcm/debug-logger.tsx
  src/app/_components/fcm/fcm-listener.tsx
  src/app/_utils/dev-logger.ts
  src/app/layout.tsx
  src/app/lib/firebase-notification.ts
Labels: 🐞 BugFix

#216 [Design/#215] 디자인 QA 수정 1차
  src/app/(tabs)/home/_components/carousel.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_components/badge.tsx
  src/app/_components/fixed-layout.tsx
  src/app/_components/input.tsx
  src/app/_components/main-card.tsx
  src/app/layout.tsx
Labels: 🎨 Desgin

#223 [Bug/#220] 중복 토스트 제거, css 수정
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/detail/_components/top-bar.tsx
  src/app/(fullscreen)/event-create/components/post-textarea.tsx
  src/app/(fullscreen)/event-create/components/step5-people.tsx
  src/app/(fullscreen)/event-create/components/step7-writing.tsx
  src/app/(fullscreen)/search/page.tsx
  src/app/_constants/detail.tsx
  src/app/_hooks/use-confirmed-noti.ts
  src/app/_stores/use-noti.ts
  src/app/_styles/globals.css
  src/app/_types/noti.ts
  src/middleware.ts
Labels: 🎨 Desgin, 🐞 BugFix, 📬 API

#224 fix: noti 비활성화
  src/app/(fullscreen)/detail/[id]/page.tsx
Labels: 🐞 BugFix
