Repository MOVIEBOOKIE/MOVIEBOOKIE_FE, pull requests merged in 2025-07, with the labels that each got.

#227 [Design/#226] 로딩 페이지 및 컴포넌트 분리
  src/app/(fullscreen)/event-create/components/step6-place.tsx
  src/app/_components/loading.tsx
  src/app/loading.tsx
Labels: ✨ Feature, 🎨 Desgin

#238 [Bug/#237] notification 필드가 없을 경우 수동알림표시
  public/custom-sw.js
  src/app/_components/fixed-layout.tsx
Labels: 🐞 BugFix, 🔄 Refactor

#244 [fix/noti] 모든 환경에서 fcm 토큰 등록하도록
  src/app/(tabs)/home/page.tsx
Labels: 🐞 BugFix

#249 [Feature/#248] 인트로 연결
  public/images/custom-bg.webp
  public/manifest.json
  src/app/(fullscreen)/intro/page.tsx
Labels: ✨ Feature

#253 [Bug/#247] 알림탭 전제조회 api , 디자인 변경사항 반영
  public/custom-sw.js
  public/images/trait/movie1.png
  src/app/(fullscreen)/trait/result/page.tsx
  src/app/(tabs)/event/_components/ticket-card.tsx
  src/app/(tabs)/home/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/(tabs)/notifications/components/get-status-bytitle.ts
  src/app/(tabs)/notifications/components/item.tsx
  src/app/(tabs)/notifications/components/target-url.ts
  src/app/(tabs)/notifications/page.tsx
  src/app/_components/input.tsx
  src/app/_components/main-card.tsx
  src/app/_hooks/fcm/use-fcm.ts
Labels: 🎨 Desgin, 📬 API

#256 [Bug/#254] 새 알림조회 api연결, 알림 뱃지 표시
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/trait/page.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/(tabs)/notifications/components/get-status-bytitle.ts
  src/app/(tabs)/notifications/components/item.tsx
  src/app/(tabs)/notifications/components/target-url.ts
  src/app/(tabs)/notifications/page.tsx
  src/app/_components/bottom-navibar.tsx
  src/app/_components/fixed-layout.tsx
  src/app/_hooks/fcm/use-fcm-handler.ts
  src/app/_stores/use-noti.ts
  src/app/_styles/globals.css
Labels: 🐞 BugFix, 📬 API

#259 [Design/#258] 디테일 페이지 디자인 수정
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/detail/_components/information-tab.tsx
  src/app/_components/button.tsx
  src/app/_components/detail-content.tsx
Labels: 🎨 Desgin

#266 [Design/#265] 카카오로그인 에러처리, 생성버튼 추가, 유형결과 페이지 라우터추가
  src/app/(fullscreen)/category/[category]/client.tsx
  src/app/(fullscreen)/trait/result/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/_components/fixed-layout.tsx
  src/app/_hooks/onboarding/use-kakao-login.ts
Labels: 🎨 Desgin, 🐞 BugFix

#276 [Feature/#272] 리스트 UI 스켈레톤 처리
  src/app/(fullscreen)/event-create/_components/cinema-skeleton-card.tsx
  src/app/(fullscreen)/event-create/components/step6-place.tsx
  src/app/(tabs)/event/_components/ticket-skeleton-card.tsx
  src/app/(tabs)/event/_components/ticket-tab.tsx
Labels: ✨ Feature

#278 [Refactor/#277] 로딩중 버튼 스피너 추가
  next.config.ts
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/event/success/_components/client.tsx
  src/app/(fullscreen)/feedback/result/components/feedbackpage.tsx
  src/app/(fullscreen)/intro/page.tsx
  src/app/(fullscreen)/login/kakao/page.tsx
  src/app/(tabs)/notifications/page.tsx
  src/app/_components/button.tsx
  src/app/_components/fixed-layout.tsx
  src/app/_context/loading-context.tsx
  src/app/_hooks/fcm/use-fcm.ts
  src/app/error.tsx
  src/app/layout.tsx
  src/icons/index.tsx
  src/icons/ui/empty-noti.svg
Labels: 🎨 Desgin, 🐞 BugFix

#284 [Refactor/#283] 탈퇴 요청, 실패시 모달표시, QA 반영
  next.config.ts
  public/images/event-banner.png
  public/images/event-banner.webp
  src/app/(fullscreen)/(my-page)/privacy-policy/page.tsx
  src/app/(fullscreen)/(my-page)/terms-of-service/page.tsx
  src/app/(fullscreen)/(my-page)/withdraw/page.tsx
  src/app/(fullscreen)/event-create/components/step5-people.tsx
  src/app/(fullscreen)/verify/verify-number/page.tsx
  src/app/(tabs)/event/page.tsx
  src/app/(tabs)/home/page.tsx
  src/app/(tabs)/my-page/page.tsx
  src/app/(tabs)/notifications/page.tsx
  src/app/_components/fixed-layout.tsx
  src/app/_components/main-card.tsx
  src/app/_components/modal.tsx
  src/app/_constants/categories.ts
  src/app/_context/toast-context.tsx
  src/app/_hooks/fcm/use-fcm-handler.ts
  src/app/_hooks/use-smart-noti-polling.ts
  src/app/layout.tsx
Labels: 🐞 BugFix, 📬 API, 🔄 Refactor

#287 [Bug/#286] 이벤트탭 무한스크롤 해결, QA 반영
  src/app/(fullscreen)/event-create/components/step5-people.tsx
  src/app/(fullscreen)/feedback/result/components/feedbackpage.tsx
  src/app/(tabs)/event/_components/event-tabs.tsx
  src/app/(tabs)/home/page.tsx
  src/app/_hooks/events/use-event-tab-query.ts
  src/app/layout.tsx
Labels: 🐞 BugFix, 🔄 Refactor

#294 [Bug/#293] 에러 페이지 수정
  src/app/_apis/register-fcm-token.ts
  src/app/_context/loading-context.tsx
  src/app/_context/toast-context.tsx
Labels: 🐞 BugFix

#295 [Bug/#273] 빌드오류 해결
  src/app/(fullscreen)/detail/[id]/page.tsx
  src/app/(fullscreen)/trait/result/page.tsx
  src/app/_context/loading-context.tsx
Labels: 🐞 BugFix

#301 [Bug/#300] 기타 오류 수정
  src/app/_hooks/fcm/use-fcm-handler.ts
  src/app/_hooks/fcm/use-fcm.ts
Labels: 🐞 BugFix
